### ISSUE TITLE
Date-shifting masking number of alcoholic beverages per week in discharge summary

### ISSUE THREAD

**Issue by vjm261** [MIT-LCP/mimic-code#40]
I have found cases where the data-shifting algorithm masks the number of alcoholic beverages per week that may be of some clinical significance in the discharge summaries. Low priority issue.
An example (with added spaces to prevent markdown styling):
> She has approximately [* * 11-26 * *] alcoholic beverages per week, does not smoke..."

HADM_ID = 120167

**Comment by SichengH** [comment]
```select * from `physionet-data.mimiciii_notes.noteevents` 
where HADM_ID = 120167
and text like '%11-26%';
```

The query returns no results. Likely this problem is already solved.

**Comment by tompollard** [comment]
> The query returns no results. Likely this problem is already solved. 

@SichengH take a look at the discharge summary for `hadm_id = 120167` and you'll see that this is still an issue. 

@vincentmajor thanks for raising this. We're continuing to work on reducing the number of false positives in the text.
